version: '3.1'

services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        restart: "always"
        ports:
          - "80:80"
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
          - ./nginx/vhost/:/etc/nginx/vhost.d:ro
          - ./nginx/conf.d/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
          - ./static/:/code/static
          - ./media/:/code/media

    postgres:
        image: postgres
        volumes:
            - ./pgdb/:/var/lib/postgresql/data
        ports:
            - "5433:5432"
        env_file: ./.env

    redis:
        image: redis
        ports:
            - 6379:6379
        restart: always

    web:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/code
            - ./static/:/code/static
            - ./media/:/code/media
        depends_on:
            - "postgres"
        env_file: ./.env

    celery:
        build:
            context: .
            dockerfile: celery.dockerfile
        volumes:
            - .:/code
        command: celery -A food_stories worker --beat --scheduler django --loglevel=info
        links:
            - redis
            - postgres
        depends_on:
            - "redis"
            - "postgres"
        env_file: ./.env

networks:
  default:
    external:
      name: nginx-proxy